### ISSUE TITLE
实例demo的效果不错

### ISSUE THREAD

**Issue by chengxianghe** [unixzii/CVTouchHints#1]
感谢作者的开源,方便的话可以分享一下完整的demo么? 只是觉得那个分页效果也不错...

**Comment by unixzii** [comment]
完整项目很大，我拿了一小部分出来改成 demo，你可以给我你的邮箱，我把分页那部分发给你。

**Comment by chengxianghe** [comment]
非常感谢!  邮箱:chengxianghe@outlook.commailto:chengxianghe@outlook.com
在 2016年6月16日，下午6:08，Cyandev <notifications@github.com<mailto:notifications@github.com>> 写道：

完整项目很大，我拿了一小部分出来改成 demo，你可以给我你的邮箱，我把分页那部分发给你。

**Comment by unixzii** [comment]
已经发出去了，说明什么都在邮件里，看看收到了吗？

**Comment by chengxianghe** [comment]
已经收到了，再次感谢！

**Comment by unixzii** [comment]
恩，不客气。
